AWSTemplateFormatVersion: '2010-09-09'
Description: 'Spokhand Sign Language Recognition Infrastructure'

Parameters:
  BucketName:
    Type: String
    Default: spokhand-data
    Description: Name of the existing S3 bucket

Resources:
  # Lambda Function for processing
  SignLanguageProcessor:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: spokhand-processor
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Code:
        S3Bucket: !Ref BucketName
        S3Key: lambda/lambda_function.zip
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref BucketName
      Timeout: 300
      MemorySize: 512

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${BucketName}/*'

  # S3 Event Notification to Lambda
  S3ToLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt SignLanguageProcessor.Arn
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub 'arn:aws:s3:::${BucketName}'

  # Add notification configuration to the existing bucket
  BucketNotificationConfig:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowLambdaInvocation
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: 
              - s3:PutObject
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${BucketName}/*'

Outputs:
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref SignLanguageProcessor
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt SignLanguageProcessor.Arn 